apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order-service
  labels:
    cloud.googleapis.com/location: asia-south1
  annotations:
    run.googleapis.com/ingress: internal
    run.googleapis.com/ingress-status: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '2'
        autoscaling.knative.dev/maxScale: '50'
        run.googleapis.com/cloudsql-instances: PROJECT_ID:asia-south1:trading-platform-db-prod
        run.googleapis.com/vpc-access-connector: trading-platform-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 20
      timeoutSeconds: 300
      serviceAccountName: trading-platform-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - name: order-service
        image: gcr.io/PROJECT_ID/order-service:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: latest
        - name: REDIS_PORT
          value: '6379'
        - name: ANGEL_ONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: angel-one-api-key
              key: latest
        - name: ENVIRONMENT
          value: 'production'
        resources:
          limits:
            cpu: '1000m'
            memory: '1Gi'
          requests:
            cpu: '250m'
            memory: '256Mi'
  traffic:
  - percent: 100
    latestRevision: true
